sylius_grid:
    grids:
        sylius_price_history_admin_channel_pricing_log_entry:
            driver:
                name: doctrine/orm
                options:
                    class: '%sylius_price_history.model.channel_pricing_log_entry.class%'
                    repository:
                        method: createByChannelPricingIdListQueryBuilder
                        arguments: [$channelPricingId]
            fields:
                price:
                    type: twig
                    label: sylius.ui.price
                    path: .
                    options:
                        template: '@SyliusPriceHistoryPlugin/Admin/ChannelPricingLogEntry/Grid/Field/price.html.twig'
                originalPrice:
                    type: twig
                    label: sylius.ui.original_price
                    path: .
                    options:
                        template: '@SyliusPriceHistoryPlugin/Admin/ChannelPricingLogEntry/Grid/Field/originalPrice.html.twig'
                loggedAt:
                    type: datetime
                    label: sylius.ui.logged_at
            filters:
                loggedAt:
                    type: date
                    label: sylius.ui.logged_at
