# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

# TODO: Remove this file when support for Sylius 1.11 is dropped.
'%sylius.model.channel.class%':
    collectionOperations:
        admin_post:
            method: POST
            path: /admin/channels
            validation_groups: ['sylius']
            denormalization_context:
                groups: ['admin:channel:create']
    itemOperations:
        admin_put:
            method: PUT
            path: /admin/channels/{code}
            validation_groups: ['sylius']
            denormalization_context:
                groups: ['admin:channel:update']
        admin_exclude_taxon:
            method: PUT
            path: /admin/channels/{code}/exclude-taxon
            messenger: input
            input: Sylius\PriceHistoryPlugin\Application\Message\ExcludeTaxonFromShowingLowestPrice
            denormalization_context:
                groups: ['admin:channel:exclude-taxon']
            normalization_context:
                groups: ['admin:channel:read']
            openapi_context:
                summary: Exclude taxon from showing lowest price in channel
        admin_remove_taxon_exclusion:
            method: PUT
            path: /admin/channels/{code}/remove-taxon-exclusion
            messenger: input
            input: Sylius\PriceHistoryPlugin\Application\Message\RemoveTaxonExclusionFromShowingLowestPrice
            denormalization_context:
                groups: ['admin:channel:exclude-taxon']
            normalization_context:
                groups: ['admin:channel:read']
            openapi_context:
                summary: Remove taxon exclusion from showing lowest price in channel
